version: '2'
services:
  data:
    container_name: tensorflow-data
    image: debian:jessie
    command: 'chown 1000:1000 /code -R'
    volumes:
      - code-volume:/code
  app:
    container_name: tensorflow-app
    build: app
    volumes:
      - ~/.ssh:/home/dev/.ssh
      - ~/.gitconfig:/home/dev/.gitconfig
      - .:/code/baby-learning/docker
      - .zsh_history:/home/dev/.zsh_history
    volumes_from:
      - data
    ports:
      - 8888:8888
volumes:
  code-volume:
    driver: local
