version: '2'
services:
  dev:
    container_name: tensorflow-dev
    build: dev
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - ~/.ssh:/home/dev/.ssh
      - ~/.gitconfig:/home/dev/.gitconfig
      - /boxes/pycharm:/home/dev/pycharm
      - /boxes/.PyCharmCE2016.3:/home/dev/.PyCharmCE2016.3
      - /boxes/.PyCharmCE.java:/home/dev/.java
      - .:/code/baby-learning/docker
      - .zsh_history:/home/dev/.zsh_history
      - /tmp/.X11-unix:/tmp/.X11-unix
    volumes_from:
      - data
    ports:
      - 8888:8888
      - 5000:5000
